import { describe, expect, it, vi } from 'vitest';
import { sanitizeHtml } from '../../src/security/htmlPolicy';

describe('htmlPolicy', () => {
    it('removes scripts and event handler attributes', () => {
        expect(sanitizeHtml('<p onclick="alert(1)">Hello<script>alert(1)</script></p>')).toBe(
            '<p>Hello</p>',
        );
    });

    it('removes dangerous link and image URLs', () => {
        const html = sanitizeHtml(
            '<a href="javascript:alert(1)">bad</a><img src="javascript:alert(1)" alt="x">',
        );

        expect(html).toBe('<a>bad</a><img alt="x">');
    });

    it('removes iframe by default', () => {
        expect(
            sanitizeHtml('<p>before</p><iframe src="https://video.example/embed"></iframe>'),
        ).toBe('<p>before</p>');
    });

    it('keeps iframe only when enabled and host is allowlisted', () => {
        expect(
            sanitizeHtml(
                '<iframe src="https://video.example/embed" allowfullscreen></iframe><iframe src="https://evil.example/embed"></iframe>',
                {
                    iframe: {
                        enabled: true,
                        allowedHosts: ['video.example'],
                    },
                },
            ),
        ).toBe('<iframe src="https://video.example/embed" allowfullscreen=""></iframe>');
    });

    it('keeps safe data attributes but removes unsafe style declarations', () => {
        expect(
            sanitizeHtml('<p data-node-id="abc" style="background:url(javascript:alert(1))">x</p>'),
        ).toBe('<p data-node-id="abc">x</p>');
    });

    it('keeps safe color style declarations generated by editor marks', () => {
        expect(
            sanitizeHtml(
                '<p style="text-align: center; color: #2563eb; background-color: #fef08a; position: fixed">x</p>',
            ),
        ).toBe('<p style="text-align: center; color: #2563eb; background-color: #fef08a">x</p>');
    });

    it('sanitizes without a browser document during SSR module evaluation', async () => {
        vi.resetModules();
        vi.stubGlobal('window', undefined);
        vi.stubGlobal('document', undefined);

        try {
            const { sanitizeHtml: sanitizeHtmlWithoutDom } =
                await import('../../src/security/htmlPolicy');

            expect(
                sanitizeHtmlWithoutDom(
                    '<p onclick="alert(1)" style="color: #2563eb; position: fixed">Hello<script>alert(1)</script></p>',
                ),
            ).toBe('<p style="color: #2563eb">Hello</p>');
        } finally {
            vi.unstubAllGlobals();
        }
    });
});
